//! Curated FieldSpec table for `MarketState` — descriptions come from
//! field doc-comments; unit / session scope / freshness / cost are
//! annotated here so the Desk Catalog cannot drift from runtime state.
//!
//! Regenerate skeleton: `python scripts/gen_catalog_fields.py`

use super::types::*;

/// Annotated specs for every `MarketState` field (snake_case rust_field).
pub(crate) fn market_state_field_specs() -> Vec<FieldSpec> {
    vec![
        FieldSpec {
            id: "market.location_structure.lastPrice",
            rust_field: "last_price",
            name: "lastPrice",
            domain_id: "location_structure",
            description: "Most recent trade price.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.bid",
            rust_field: "bid",
            name: "bid",
            domain_id: "location_structure",
            description: "Current best bid price.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.ask",
            rust_field: "ask",
            name: "ask",
            domain_id: "location_structure",
            description: "Current best ask price.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.vwap",
            rust_field: "vwap",
            name: "vwap",
            domain_id: "location_structure",
            description: "Session volume-weighted average price.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.vwap1SdUpper",
            rust_field: "vwap_1sd_upper",
            name: "vwap1SdUpper",
            domain_id: "location_structure",
            description: "VWAP plus one standard deviation.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vwap1SdLower",
            rust_field: "vwap_1sd_lower",
            name: "vwap1SdLower",
            domain_id: "location_structure",
            description: "VWAP minus one standard deviation.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vwap2SdUpper",
            rust_field: "vwap_2sd_upper",
            name: "vwap2SdUpper",
            domain_id: "location_structure",
            description: "VWAP plus two standard deviations.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vwap2SdLower",
            rust_field: "vwap_2sd_lower",
            name: "vwap2SdLower",
            domain_id: "location_structure",
            description: "VWAP minus two standard deviations.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vwap3SdUpper",
            rust_field: "vwap_3sd_upper",
            name: "vwap3SdUpper",
            domain_id: "location_structure",
            description: "VWAP plus three standard deviations.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vwap3SdLower",
            rust_field: "vwap_3sd_lower",
            name: "vwap3SdLower",
            domain_id: "location_structure",
            description: "VWAP minus three standard deviations.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.vaHigh",
            rust_field: "va_high",
            name: "vaHigh",
            domain_id: "location_structure",
            description: "TPO value area high (70% of TPOs).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.vaLow",
            rust_field: "va_low",
            name: "vaLow",
            domain_id: "location_structure",
            description: "TPO value area low (70% of TPOs).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.poc",
            rust_field: "poc",
            name: "poc",
            domain_id: "location_structure",
            description: "Point of control - price with highest TPO count.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.dnvaHigh",
            rust_field: "dnva_high",
            name: "dnvaHigh",
            domain_id: "location_structure",
            description: "Delta neutral value area high (70% of absolute delta).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.dnvaLow",
            rust_field: "dnva_low",
            name: "dnvaLow",
            domain_id: "location_structure",
            description: "Delta neutral value area low (70% of absolute delta).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.dnp",
            rust_field: "dnp",
            name: "dnp",
            domain_id: "location_structure",
            description: "Delta Neutral Pivot - midpoint of DNVA high and low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.flow.sessionDelta",
            rust_field: "session_delta",
            name: "sessionDelta",
            domain_id: "flow",
            description: "Segment delta: Asia-only, London-only, or RTH-only. Resets at Asia→London (2 AM) and RTH↔Globex.",
            unit: Unit::Contracts,
            session_scope: SessionScope::Segment,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.globexDelta",
            rust_field: "globex_delta",
            name: "globexDelta",
            domain_id: "flow",
            description: "Combined Globex delta (Asia + London) from 6 PM ET. Only present during Globex; null during RTH.",
            unit: Unit::Contracts,
            session_scope: SessionScope::Globex,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.cumulativeDelta",
            rust_field: "cumulative_delta",
            name: "cumulativeDelta",
            domain_id: "flow",
            description: "Running cumulative delta across sessions.",
            unit: Unit::Contracts,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorDayHigh",
            rust_field: "prior_day_high",
            name: "priorDayHigh",
            domain_id: "location_structure",
            description: "Previous RTH session high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.priorDayLow",
            rust_field: "prior_day_low",
            name: "priorDayLow",
            domain_id: "location_structure",
            description: "Previous RTH session low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.priorDayClose",
            rust_field: "prior_day_close",
            name: "priorDayClose",
            domain_id: "location_structure",
            description: "Previous RTH session closing price.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.priorVaHigh",
            rust_field: "prior_va_high",
            name: "priorVaHigh",
            domain_id: "location_structure",
            description: "Previous session value area high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorVaLow",
            rust_field: "prior_va_low",
            name: "priorVaLow",
            domain_id: "location_structure",
            description: "Previous session value area low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorPoc",
            rust_field: "prior_poc",
            name: "priorPoc",
            domain_id: "location_structure",
            description: "Previous session point of control.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorDnvaHigh",
            rust_field: "prior_dnva_high",
            name: "priorDnvaHigh",
            domain_id: "location_structure",
            description: "Prior RTH session DNVA high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorDnvaLow",
            rust_field: "prior_dnva_low",
            name: "priorDnvaLow",
            domain_id: "location_structure",
            description: "Prior RTH session DNVA low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.priorDnp",
            rust_field: "prior_dnp",
            name: "priorDnp",
            domain_id: "location_structure",
            description: "Prior RTH session DNP.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.overnightHigh",
            rust_field: "overnight_high",
            name: "overnightHigh",
            domain_id: "location_structure",
            description: "Overnight (Globex) session high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.overnightLow",
            rust_field: "overnight_low",
            name: "overnightLow",
            domain_id: "location_structure",
            description: "Overnight (Globex) session low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.sessionHigh",
            rust_field: "session_high",
            name: "sessionHigh",
            domain_id: "location_structure",
            description: "Current RTH session high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.sessionLow",
            rust_field: "session_low",
            name: "sessionLow",
            domain_id: "location_structure",
            description: "Current RTH session low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.rthClosePrice",
            rust_field: "rth_close_price",
            name: "rthClosePrice",
            domain_id: "location_structure",
            description: "Last RTH trade price used as session close.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.globexOr30High",
            rust_field: "globex_or30_high",
            name: "globexOr30High",
            domain_id: "location_structure",
            description: "Globex OR30 high (18:00-18:30 ET).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Globex,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.globexOr30Low",
            rust_field: "globex_or30_low",
            name: "globexOr30Low",
            domain_id: "location_structure",
            description: "Globex OR30 low (18:00-18:30 ET).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Globex,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.londonOr60High",
            rust_field: "london_or60_high",
            name: "londonOr60High",
            domain_id: "location_structure",
            description: "London OR60 high (02:00-03:00 ET).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Globex,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.londonOr60Low",
            rust_field: "london_or60_low",
            name: "londonOr60Low",
            domain_id: "location_structure",
            description: "London OR60 low (02:00-03:00 ET).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Globex,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.orHigh",
            rust_field: "or_high",
            name: "orHigh",
            domain_id: "location_structure",
            description: "Opening range high (first 30 minutes of RTH).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.orLow",
            rust_field: "or_low",
            name: "orLow",
            domain_id: "location_structure",
            description: "Opening range low (first 30 minutes of RTH).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.ibHigh",
            rust_field: "ib_high",
            name: "ibHigh",
            domain_id: "location_structure",
            description: "Initial balance high (first 60 minutes of RTH).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.ibLow",
            rust_field: "ib_low",
            name: "ibLow",
            domain_id: "location_structure",
            description: "Initial balance low (first 60 minutes of RTH).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.flow.tapePace5S",
            rust_field: "tape_pace_5s",
            name: "tapePace5S",
            domain_id: "flow",
            description: "Rolling 5-second tape pace (ticks/sec) when the window has sufficient coverage.",
            unit: Unit::TicksPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapePace30S",
            rust_field: "tape_pace_30s",
            name: "tapePace30S",
            domain_id: "flow",
            description: "Rolling 30-second tape pace (ticks/sec) when the window has sufficient coverage.",
            unit: Unit::TicksPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapePace5M",
            rust_field: "tape_pace_5m",
            name: "tapePace5M",
            domain_id: "flow",
            description: "Rolling 5-minute tape pace (ticks/sec) when the window has sufficient coverage.",
            unit: Unit::TicksPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeAcceleration",
            rust_field: "tape_acceleration",
            name: "tapeAcceleration",
            domain_id: "flow",
            description: "Smoothed and normalized tape acceleration.",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeRawAcceleration",
            rust_field: "tape_raw_acceleration",
            name: "tapeRawAcceleration",
            domain_id: "flow",
            description: "Raw 5s minus 30s pace spread for debugging and calibration.",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.pacePercentile",
            rust_field: "pace_percentile",
            name: "pacePercentile",
            domain_id: "flow",
            description: "Current pace percentile vs session distribution (0.0-1.0).",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeRollingPercentile",
            rust_field: "tape_rolling_percentile",
            name: "tapeRollingPercentile",
            domain_id: "flow",
            description: "Current pace percentile vs the recent rolling intraday distribution (0.0-1.0).",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeVolumePerSec5S",
            rust_field: "tape_volume_per_sec_5s",
            name: "tapeVolumePerSec5S",
            domain_id: "flow",
            description: "Rolling 5-second tape volume pace (contracts/sec).",
            unit: Unit::ContractsPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeVolumePerSec30S",
            rust_field: "tape_volume_per_sec_30s",
            name: "tapeVolumePerSec30S",
            domain_id: "flow",
            description: "Rolling 30-second tape volume pace (contracts/sec).",
            unit: Unit::ContractsPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeVolumePerSec5M",
            rust_field: "tape_volume_per_sec_5m",
            name: "tapeVolumePerSec5M",
            domain_id: "flow",
            description: "Rolling 5-minute tape volume pace (contracts/sec).",
            unit: Unit::ContractsPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeRegimeTicksPerSec30MEma",
            rust_field: "tape_regime_ticks_per_sec_30m_ema",
            name: "tapeRegimeTicksPerSec30MEma",
            domain_id: "flow",
            description: "Longer-horizon tape regime baseline (ticks/sec EMA).",
            unit: Unit::TicksPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeRegimeVolumePerSec30MEma",
            rust_field: "tape_regime_volume_per_sec_30m_ema",
            name: "tapeRegimeVolumePerSec30MEma",
            domain_id: "flow",
            description: "Longer-horizon tape regime baseline (volume/sec EMA).",
            unit: Unit::ContractsPerSec,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeCoverage5S",
            rust_field: "tape_coverage_5s",
            name: "tapeCoverage5S",
            domain_id: "flow",
            description: "Window coverage ratio for the 5-second tape window (0.0-1.0).",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeCoverage30S",
            rust_field: "tape_coverage_30s",
            name: "tapeCoverage30S",
            domain_id: "flow",
            description: "Window coverage ratio for the 30-second tape window (0.0-1.0).",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeCoverage5M",
            rust_field: "tape_coverage_5m",
            name: "tapeCoverage5M",
            domain_id: "flow",
            description: "Window coverage ratio for the 5-minute tape window (0.0-1.0).",
            unit: Unit::Ratio,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeValid5S",
            rust_field: "tape_valid_5s",
            name: "tapeValid5S",
            domain_id: "flow",
            description: "Whether the 5-second tape window has enough event-time coverage to trust.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeValid30S",
            rust_field: "tape_valid_30s",
            name: "tapeValid30S",
            domain_id: "flow",
            description: "Whether the 30-second tape window has enough event-time coverage to trust.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeValid5M",
            rust_field: "tape_valid_5m",
            name: "tapeValid5M",
            domain_id: "flow",
            description: "Whether the 5-minute tape window has enough event-time coverage to trust.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeWindowAnchorTimestampMs",
            rust_field: "tape_window_anchor_timestamp_ms",
            name: "tapeWindowAnchorTimestampMs",
            domain_id: "flow",
            description: "Event-time anchor timestamp for the tape snapshot (ms).",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeLastTradeTimestampMs",
            rust_field: "tape_last_trade_timestamp_ms",
            name: "tapeLastTradeTimestampMs",
            domain_id: "flow",
            description: "Timestamp of the last trade included in the tape snapshot (ms).",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeEventTimeLagMs",
            rust_field: "tape_event_time_lag_ms",
            name: "tapeEventTimeLagMs",
            domain_id: "flow",
            description: "Event-time lag between tape anchor and last trade (ms).",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.tapeDwellAtCurrentPriceMs",
            rust_field: "tape_dwell_at_current_price_ms",
            name: "tapeDwellAtCurrentPriceMs",
            domain_id: "flow",
            description: "Dwell time at the current price level using the event-time anchor.",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.imbalanceCount",
            rust_field: "imbalance_count",
            name: "imbalanceCount",
            domain_id: "flow",
            description: "Recent stacked imbalance count.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.absorptionEventCount",
            rust_field: "absorption_event_count",
            name: "absorptionEventCount",
            domain_id: "flow",
            description: "Number of recent absorption events.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.confirmedAbsorptionEventCount",
            rust_field: "confirmed_absorption_event_count",
            name: "confirmedAbsorptionEventCount",
            domain_id: "flow",
            description: "Number of confirmed absorption events.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.confirmedExhaustionEventCount",
            rust_field: "confirmed_exhaustion_event_count",
            name: "confirmedExhaustionEventCount",
            domain_id: "flow",
            description: "Number of confirmed exhaustion events.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.confirmedDeltaDivergenceEventCount",
            rust_field: "confirmed_delta_divergence_event_count",
            name: "confirmedDeltaDivergenceEventCount",
            domain_id: "flow",
            description: "Number of confirmed delta divergence events.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.hasRecentConfirmedAbsorption",
            rust_field: "has_recent_confirmed_absorption",
            name: "hasRecentConfirmedAbsorption",
            domain_id: "flow",
            description: "Whether there is a still-live confirmed absorption near current price.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedAbsorptionPrice",
            rust_field: "recent_confirmed_absorption_price",
            name: "recentConfirmedAbsorptionPrice",
            domain_id: "flow",
            description: "Price of the most recent confirmed absorption considered live for evaluation.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedAbsorptionDirection",
            rust_field: "recent_confirmed_absorption_direction",
            name: "recentConfirmedAbsorptionDirection",
            domain_id: "flow",
            description: "Direction implied by the most recent confirmed absorption.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedAbsorptionAgeMs",
            rust_field: "recent_confirmed_absorption_age_ms",
            name: "recentConfirmedAbsorptionAgeMs",
            domain_id: "flow",
            description: "Age of the most recent confirmed absorption in milliseconds.",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedAbsorptionDistanceTicks",
            rust_field: "recent_confirmed_absorption_distance_ticks",
            name: "recentConfirmedAbsorptionDistanceTicks",
            domain_id: "flow",
            description: "Distance from current price to the most recent confirmed absorption, in ticks.",
            unit: Unit::Ticks,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.hasRecentInvalidatedAbsorption",
            rust_field: "has_recent_invalidated_absorption",
            name: "hasRecentInvalidatedAbsorption",
            domain_id: "flow",
            description: "Whether a recently *invalidated* absorption is live (IDEA-012 failure / vacuum).",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentInvalidatedAbsorptionPrice",
            rust_field: "recent_invalidated_absorption_price",
            name: "recentInvalidatedAbsorptionPrice",
            domain_id: "flow",
            description: "Price of the most recent invalidated absorption.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentInvalidatedAbsorptionDirection",
            rust_field: "recent_invalidated_absorption_direction",
            name: "recentInvalidatedAbsorptionDirection",
            domain_id: "flow",
            description: "Direction implied by the most recent invalidated absorption.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentInvalidatedAbsorptionAgeMs",
            rust_field: "recent_invalidated_absorption_age_ms",
            name: "recentInvalidatedAbsorptionAgeMs",
            domain_id: "flow",
            description: "Age of the most recent invalidated absorption (since it failed), in milliseconds.",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentInvalidatedAbsorptionDistanceTicks",
            rust_field: "recent_invalidated_absorption_distance_ticks",
            name: "recentInvalidatedAbsorptionDistanceTicks",
            domain_id: "flow",
            description: "Distance from current price to the most recent invalidated absorption, in ticks.",
            unit: Unit::Ticks,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.hasRecentConfirmedExhaustion",
            rust_field: "has_recent_confirmed_exhaustion",
            name: "hasRecentConfirmedExhaustion",
            domain_id: "flow",
            description: "Whether there is a still-live confirmed exhaustion signal.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedExhaustionPrice",
            rust_field: "recent_confirmed_exhaustion_price",
            name: "recentConfirmedExhaustionPrice",
            domain_id: "flow",
            description: "Price of the most recent confirmed exhaustion considered live for evaluation.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedExhaustionDirection",
            rust_field: "recent_confirmed_exhaustion_direction",
            name: "recentConfirmedExhaustionDirection",
            domain_id: "flow",
            description: "Direction implied by the most recent confirmed exhaustion.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.recentConfirmedExhaustionAgeMs",
            rust_field: "recent_confirmed_exhaustion_age_ms",
            name: "recentConfirmedExhaustionAgeMs",
            domain_id: "flow",
            description: "Age of the most recent confirmed exhaustion in milliseconds.",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.avgTradeSize",
            rust_field: "avg_trade_size",
            name: "avgTradeSize",
            domain_id: "flow",
            description: "Average trade size for current session.",
            unit: Unit::Contracts,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.or5High",
            rust_field: "or5_high",
            name: "or5High",
            domain_id: "location_structure",
            description: "5-min OR high.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.or5Low",
            rust_field: "or5_low",
            name: "or5Low",
            domain_id: "location_structure",
            description: "5-min OR low.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.or5Mid",
            rust_field: "or5_mid",
            name: "or5Mid",
            domain_id: "location_structure",
            description: "5-min OR midpoint (key level).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.or5Locked",
            rust_field: "or5_locked",
            name: "or5Locked",
            domain_id: "location_structure",
            description: "Whether OR5 range is locked (past 5 minutes).",
            unit: Unit::Bool,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.or5BreakDirection",
            rust_field: "or5_break_direction",
            name: "or5BreakDirection",
            domain_id: "location_structure",
            description: "Break direction from OR5.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.or5MidRetested",
            rust_field: "or5_mid_retested",
            name: "or5MidRetested",
            domain_id: "location_structure",
            description: "Whether price has retested the OR5 midpoint after a break.",
            unit: Unit::Bool,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolRatio",
            rust_field: "rvol_ratio",
            name: "rvolRatio",
            domain_id: "volatility",
            description: "RVOL ratio (1.0 = tracking average). Serializes as null when unavailable.",
            unit: Unit::Ratio,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolClassification",
            rust_field: "rvol_classification",
            name: "rvolClassification",
            domain_id: "volatility",
            description: "RVOL classification.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolVelocity",
            rust_field: "rvol_velocity",
            name: "rvolVelocity",
            domain_id: "volatility",
            description: "RVOL velocity: rate of change of ratio per 5-min bucket.",
            unit: Unit::Ratio,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolAcceleration",
            rust_field: "rvol_acceleration",
            name: "rvolAcceleration",
            domain_id: "volatility",
            description: "RVOL acceleration: second derivative of ratio.",
            unit: Unit::Ratio,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolPercentile",
            rust_field: "rvol_percentile",
            name: "rvolPercentile",
            domain_id: "volatility",
            description: "RVOL percentile rank vs historical days at same time-of-day (0-100).",
            unit: Unit::Percent,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolBucketIndex",
            rust_field: "rvol_bucket_index",
            name: "rvolBucketIndex",
            domain_id: "volatility",
            description: "Current 5-minute bucket index.",
            unit: Unit::Count,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolBaselineStatus",
            rust_field: "rvol_baseline_status",
            name: "rvolBaselineStatus",
            domain_id: "volatility",
            description: "RVOL baseline quality: ok, partial, synthetic, or unavailable.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolLookbackDaysActual",
            rust_field: "rvol_lookback_days_actual",
            name: "rvolLookbackDaysActual",
            domain_id: "volatility",
            description: "Number of historical same-session curves available at the current bucket.",
            unit: Unit::Count,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolExpectedVolume",
            rust_field: "rvol_expected_volume",
            name: "rvolExpectedVolume",
            domain_id: "volatility",
            description: "Expected cumulative volume at the current bucket from the baseline.",
            unit: Unit::Contracts,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.volatility.rvolCaveat",
            rust_field: "rvol_caveat",
            name: "rvolCaveat",
            domain_id: "volatility",
            description: "Human-readable caveat when the baseline is partial or unavailable.",
            unit: Unit::Text,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.dayType",
            rust_field: "day_type",
            name: "dayType",
            domain_id: "location_structure",
            description: "Current day type classification.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.profileShape",
            rust_field: "profile_shape",
            name: "profileShape",
            domain_id: "location_structure",
            description: "Profile shape.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.balanceState",
            rust_field: "balance_state",
            name: "balanceState",
            domain_id: "location_structure",
            description: "Balance state.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.singlePrintsDirection",
            rust_field: "single_prints_direction",
            name: "singlePrintsDirection",
            domain_id: "location_structure",
            description: "Single prints direction relative to POC.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.ibExtensionState",
            rust_field: "ib_extension_state",
            name: "ibExtensionState",
            domain_id: "location_structure",
            description: "Live 0.5x IB extension state: \"None\" | \"UpOnly\" | \"DownOnly\" | \"BothSides\".",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.location_structure.regime",
            rust_field: "regime",
            name: "regime",
            domain_id: "location_structure",
            description: "Computed session regime used to gate setup-family eligibility.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Rth,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.flow.pinchEventCount",
            rust_field: "pinch_event_count",
            name: "pinchEventCount",
            domain_id: "flow",
            description: "Number of recent pinch events.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.cross_market.inventoryState",
            rust_field: "inventory_state",
            name: "inventoryState",
            domain_id: "cross_market",
            description: "Cross-session inventory state.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.cross_market.inventoryDirection",
            rust_field: "inventory_direction",
            name: "inventoryDirection",
            domain_id: "cross_market",
            description: "Cross-session inventory direction.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.cross_market.sessionsInTrend",
            rust_field: "sessions_in_trend",
            name: "sessionsInTrend",
            domain_id: "cross_market",
            description: "Consecutive sessions with same-direction delta.",
            unit: Unit::Count,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.activeZoneCount",
            rust_field: "active_zone_count",
            name: "activeZoneCount",
            domain_id: "response",
            description: "Number of active acceleration zones.",
            unit: Unit::Count,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.rebidZoneNear",
            rust_field: "rebid_zone_near",
            name: "rebidZoneNear",
            domain_id: "response",
            description: "A non-failed rebid (buy/support) zone is within proximity of price.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.reofferZoneNear",
            rust_field: "reoffer_zone_near",
            name: "reofferZoneNear",
            domain_id: "response",
            description: "A non-failed reoffer (sell/resistance) zone is within proximity of price.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.rebidZoneRetested",
            rust_field: "rebid_zone_retested",
            name: "rebidZoneRetested",
            domain_id: "response",
            description: "A rebid zone near price is at Retested status - the entry trigger.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.reofferZoneRetested",
            rust_field: "reoffer_zone_retested",
            name: "reofferZoneRetested",
            domain_id: "response",
            description: "A reoffer zone near price is at Retested status - the entry trigger.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.rebidZoneHeld",
            rust_field: "rebid_zone_held",
            name: "rebidZoneHeld",
            domain_id: "response",
            description: "A rebid zone near price is at Held status.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.reofferZoneHeld",
            rust_field: "reoffer_zone_held",
            name: "reofferZoneHeld",
            domain_id: "response",
            description: "A reoffer zone near price is at Held status.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.nearestZoneDirection",
            rust_field: "nearest_zone_direction",
            name: "nearestZoneDirection",
            domain_id: "response",
            description: "Direction of the nearest non-failed zone (\"buy\"/\"sell\"), if any.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.nearestZoneStatus",
            rust_field: "nearest_zone_status",
            name: "nearestZoneStatus",
            domain_id: "response",
            description: "Lifecycle status of the nearest non-failed zone, if any.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.nearestZoneDistanceTicks",
            rust_field: "nearest_zone_distance_ticks",
            name: "nearestZoneDistanceTicks",
            domain_id: "response",
            description: "Distance in ticks to the nearest non-failed zone, if any.",
            unit: Unit::Ticks,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.rebidZoneLow",
            rust_field: "rebid_zone_low",
            name: "rebidZoneLow",
            domain_id: "response",
            description: "Band low of the nearest rebid (buy/support) zone - exit anchor for longs.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.rebidZoneHigh",
            rust_field: "rebid_zone_high",
            name: "rebidZoneHigh",
            domain_id: "response",
            description: "Band high of the nearest rebid (buy/support) zone - exit anchor for longs.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.reofferZoneLow",
            rust_field: "reoffer_zone_low",
            name: "reofferZoneLow",
            domain_id: "response",
            description: "Band low of the nearest reoffer (sell/resistance) zone - exit anchor for shorts.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.response.reofferZoneHigh",
            rust_field: "reoffer_zone_high",
            name: "reofferZoneHigh",
            domain_id: "response",
            description: "Band high of the nearest reoffer (sell/resistance) zone - exit anchor for shorts.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.poorHigh",
            rust_field: "poor_high",
            name: "poorHigh",
            domain_id: "location_structure",
            description: "Whether the session high is a \"poor high\" (multiple prints at extreme).",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.poorLow",
            rust_field: "poor_low",
            name: "poorLow",
            domain_id: "location_structure",
            description: "Whether the session low is a \"poor low\" (multiple prints at extreme).",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.excessHigh",
            rust_field: "excess_high",
            name: "excessHigh",
            domain_id: "location_structure",
            description: "Excess at top of profile.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.location_structure.excessLow",
            rust_field: "excess_low",
            name: "excessLow",
            domain_id: "location_structure",
            description: "Excess at bottom of profile.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legStatus",
            rust_field: "leg_status",
            name: "legStatus",
            domain_id: "flow",
            description: "Active rotation status: `none` (no trades), `insufficient` (too new/unstable), or `active` (mature).",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legDirection",
            rust_field: "leg_direction",
            name: "legDirection",
            domain_id: "flow",
            description: "Confirmed swing direction of the active rotation (`up` / `down`) when known.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legAnchorTimeMs",
            rust_field: "leg_anchor_time_ms",
            name: "legAnchorTimeMs",
            domain_id: "flow",
            description: "Timestamp (ms) when the active-leg swing extreme last printed, not the later reversal-confirmation time.",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legAnchorPrice",
            rust_field: "leg_anchor_price",
            name: "legAnchorPrice",
            domain_id: "flow",
            description: "Price of the active-leg swing extreme (last confirmed swing). Zero when `none`.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legAgeMs",
            rust_field: "leg_age_ms",
            name: "legAgeMs",
            domain_id: "flow",
            description: "Milliseconds since the active-leg swing anchor (same instant as `leg_anchor_time_ms`).",
            unit: Unit::Milliseconds,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legVolume",
            rust_field: "leg_volume",
            name: "legVolume",
            domain_id: "flow",
            description: "Traded volume in the active rotation (swing through current extreme; counter-move prints transfer to the next leg at confirmation).",
            unit: Unit::Contracts,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legNetDelta",
            rust_field: "leg_net_delta",
            name: "legNetDelta",
            domain_id: "flow",
            description: "Net delta (ask buys minus bid sells) in the active rotation (same attribution as `leg_volume`).",
            unit: Unit::Contracts,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legPoc",
            rust_field: "leg_poc",
            name: "legPoc",
            domain_id: "flow",
            description: "Volume point of control of the active leg. Zero when the rotation is `insufficient` or `none`.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legHvn",
            rust_field: "leg_hvn",
            name: "legHvn",
            domain_id: "flow",
            description: "Highest-volume node of the active leg (compact snapshot: same as `leg_poc`; no clustering).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legLvn",
            rust_field: "leg_lvn",
            name: "legLvn",
            domain_id: "flow",
            description: "Lowest-volume node of the active-leg map (excludes POC when more than one price traded).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legVaHigh",
            rust_field: "leg_va_high",
            name: "legVaHigh",
            domain_id: "flow",
            description: "Active-leg value area high (70% of leg volume, expand from volume POC among occupied prices).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legVaLow",
            rust_field: "leg_va_low",
            name: "legVaLow",
            domain_id: "flow",
            description: "Active-leg value area low (70% of leg volume, expand from volume POC among occupied prices).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legDeltaPoc",
            rust_field: "leg_delta_poc",
            name: "legDeltaPoc",
            domain_id: "flow",
            description: "Price with the largest absolute delta in the active-leg delta profile (delta-profile control).",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legPocAtSessionPoc",
            rust_field: "leg_poc_at_session_poc",
            name: "legPocAtSessionPoc",
            domain_id: "flow",
            description: "True when mature leg POC is within two ticks of the same-session TPO POC.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legPocInSessionVa",
            rust_field: "leg_poc_in_session_va",
            name: "legPocInSessionVa",
            domain_id: "flow",
            description: "True when mature leg POC sits inside the same-session TPO value area (two-tick band).",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legVaOverlapsSessionVa",
            rust_field: "leg_va_overlaps_session_va",
            name: "legVaOverlapsSessionVa",
            domain_id: "flow",
            description: "True when the mature leg VA overlaps the same-session TPO value area.",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.legPocInSessionDnva",
            rust_field: "leg_poc_in_session_dnva",
            name: "legPocInSessionDnva",
            domain_id: "flow",
            description: "True when mature leg POC sits inside the current delta-segment DNVA (two-tick band).",
            unit: Unit::Bool,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.lastLegDirection",
            rust_field: "last_leg_direction",
            name: "lastLegDirection",
            domain_id: "flow",
            description: "Direction of the last completed rotation (`up` / `down`).",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.lastLegVolume",
            rust_field: "last_leg_volume",
            name: "lastLegVolume",
            domain_id: "flow",
            description: "Traded volume of the last completed rotation (swing through that rotation's extreme; excludes the subsequent counter-move).",
            unit: Unit::Contracts,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.lastLegNetDelta",
            rust_field: "last_leg_net_delta",
            name: "lastLegNetDelta",
            domain_id: "flow",
            description: "Net delta of the last completed rotation (same attribution as `last_leg_volume`).",
            unit: Unit::Contracts,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.flow.lastLegPoc",
            rust_field: "last_leg_poc",
            name: "lastLegPoc",
            domain_id: "flow",
            description: "Volume POC of the last completed rotation.",
            unit: Unit::PricePoints,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::LiveTickAnchored,
            cost_hint: CostHint::R1,
        },
        FieldSpec {
            id: "market.identity.sessionType",
            rust_field: "session_type",
            name: "sessionType",
            domain_id: "identity",
            description: "Current session type from last tick / snapshot time: \"RTH\", \"Globex\", or \"Unknown\". During Globex, use overnightHigh/overnightLow as session range; sessionHigh/sessionLow and IB/OR/OR5 are RTH-only.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.sessionSegment",
            rust_field: "session_segment",
            name: "sessionSegment",
            domain_id: "identity",
            description: "Globex sub-session segment: \"Asia\", \"London\", or \"None\".",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.tradingDay",
            rust_field: "trading_day",
            name: "tradingDay",
            domain_id: "identity",
            description: "Trading day (YYYY-MM-DD) with a 6:00 PM ET roll.",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.rootSymbol",
            rust_field: "root_symbol",
            name: "rootSymbol",
            domain_id: "identity",
            description: "Root symbol for the active instrument family (e.g. NQ).",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.contractSymbol",
            rust_field: "contract_symbol",
            name: "contractSymbol",
            domain_id: "identity",
            description: "Resolved active contract symbol (e.g. NQM26.CME).",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.contractMonth",
            rust_field: "contract_month",
            name: "contractMonth",
            domain_id: "identity",
            description: "Contract expiry month in YYYY-MM when available.",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.symbolResolutionMode",
            rust_field: "symbol_resolution_mode",
            name: "symbolResolutionMode",
            domain_id: "identity",
            description: "Configured symbol-resolution mode.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.symbolResolutionSource",
            rust_field: "symbol_resolution_source",
            name: "symbolResolutionSource",
            domain_id: "identity",
            description: "How the contract was resolved for the active feed.",
            unit: Unit::EnumLabel,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.rolloverWarning",
            rust_field: "rollover_warning",
            name: "rolloverWarning",
            domain_id: "identity",
            description: "Roll/carry-forward warning surfaced to MCP callers.",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.carryForwardLevelsValid",
            rust_field: "carry_forward_levels_valid",
            name: "carryForwardLevelsValid",
            domain_id: "identity",
            description: "Whether prior-day carry-forward levels are safe for the active contract.",
            unit: Unit::Bool,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::SessionScoped,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.identity.priorDayContractSymbol",
            rust_field: "prior_day_contract_symbol",
            name: "priorDayContractSymbol",
            domain_id: "identity",
            description: "Contract symbol used for the current prior-day references, if any.",
            unit: Unit::Text,
            session_scope: SessionScope::CrossSession,
            freshness: FreshnessSemantics::PriorSessionCarry,
            cost_hint: CostHint::R0,
        },
        FieldSpec {
            id: "market.liquidity.domSummary",
            rust_field: "dom_summary",
            name: "domSummary",
            domain_id: "liquidity",
            description: "Compact delayed DOM summary when historical depth context is available.",
            unit: Unit::StructuredBlob,
            session_scope: SessionScope::Session,
            freshness: FreshnessSemantics::DelayedDepthOptional,
            cost_hint: CostHint::R1,
        },
    ]
}
